server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /menus/**
        - id: store
          uri: http://localhost:8082
          predicates:
            - Path=/sotreOrders/**, 
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/**, 
        - id: delivery
          uri: http://localhost:8084
          predicates:
            - Path=/deliveries/**, 
        - id: notify
          uri: http://localhost:8085
          predicates:
            - Path=/notifications/**, 
        - id: my order
          uri: http://localhost:8086
          predicates:
            - Path=, /orderStatuses/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://front:8080
          predicates:
            - Path=/orders/**, /menus/**
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/sotreOrders/**, 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/**, 
        - id: notify
          uri: http://notify:8080
          predicates:
            - Path=/notifications/**, 
        - id: my order
          uri: http://myOrder:8080
          predicates:
            - Path=, /orderStatuses/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
